name: draft-release

on:
  pull_request:
    types: [closed]

jobs:
  draft-release:
    uses: alphaprime-dev/alpha-actions/.github/workflows/draft-release.yml@e8b5a2f84a62ad40971fc6f22172f5571cf4535c
    secrets: inherit
